adafruit/Wippersnapper_Components

- components/pin/schema.json
Pins need a specified direction!
> Make pin direction a required field in schema

- .github/workflows/validate.yml
- require images to be square
- add "precision" to sensors
- allow manually running validations across all files
> New Validations

- components/i2c/vl53l0x/definition.json
Closes https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/issues/356
> Update definition.json for VL53L0X to published

- .github/workflows/validate.yml
update actions workflow to clear deprecations
> Fix Action deprecations

- components/i2c/tmp117/definition.json
This is a test of the admin check for publishing components.
The test will establish if members of the IO team in github will automatically pass the admin check on publish: true.
> Publish TMP117 component

- components/i2c/bmp280/definition.json
Flicking the switch, this component is ready for public service!
> Publish BMP280

- components/i2c/bme688/definition.json
- components/i2c/dht20/definition.json
- components/i2c/lps33hw/definition.json
- components/i2c/mpl115a2/definition.json
- components/i2c/sht41/definition.json
- components/i2c/tc74a0/definition.json
Promotes DHT20 BME688 LPS33HW MPL115A2 TC74A0 SHT41
Closes #119, #64
> Publish components

- components/i2c/am2301b/definition.json
- components/i2c/am2315c/definition.json
- components/i2c/bh1750/definition.json
- components/i2c/hts221/definition.json
- components/i2c/sgp30/definition.json
Promoting previously released components, and the latest two for guide writing.
> Publishing components

- components/i2c/ms8607/definition.json
https://www.adafruit.com/product/4716
> Publish MS8607 component

- components/i2c/mprls/definition.json
Publishes https://www.adafruit.com/product/3965
> Publish Honeywell MPRSL

- components/i2c/lps22hb/definition.json
- components/i2c/lps25hb/definition.json
Publishes LPS2x's ready for guide page
> Publish LPS22HB + LPS25HB

- components/i2c/bmp390/definition.json
> Publish BMP390

- components/i2c/ltr303/definition.json
- components/i2c/ltr329/definition.json
These have been released as part of latest release, and now the guides are being done so need published components
> Publish ltr329 + 303

- components/i2c/vl53l0x/definition.json
- components/i2c/vl6180x/definition.json
This adds the VL6180X unpublished, and tweaks the available addresses for the VL53L0X
> Add VL6180X ToF sensor

- components/i2c/adt7410/definition.json
Addresses https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/issues/529
> Update ADT7410 to include Alt I2C Addresses

- components/i2c/vcnl4020/definition.json
- components/i2c/vcnl4040/definition.json
> Update VCNL4040 and add VCNL4020

- components/i2c/vl53l4cd/definition.json
Unpublished, to be tested with WS/#550
> Add VL54L4CD

- components/i2c/vcnl4020/definition.json
- components/i2c/vcnl4040/definition.json
Releasing these so I can complete the guide pages
> Publish VCNL4020+VCNL4040

- components/pixel/neorgb/definition.json
Does this look about right @brentru
> Add NeoRGB as pixel/neopixel component

- components/pixel/neorgb/definition.json
Please include information about the component here. If you are changing an existing component, include any relevant motivation or context.
Please include a link to the sensor here.
Please include a link to the sensor's documentation page(s) or datasheet(s) here.
> Publish NeoRGB and tweak description

- components/i2c/vl53l0x/definition.json
- components/i2c/vl53l4cd/definition.json
- components/i2c/vl53l4cx/definition.json
- components/i2c/vl6180x/definition.json
While I was there, testing on staging first.
Looks alright:
> Fix remaining ToF sensor descriptions

- components/i2c/dps310/definition.json
This is a PR to fix all wippersnapper components to have respective learn guides.
[x] Correct DPS310
> Corrects Docs links for some products

- components/i2c/ds2484/definition.json
Closes https://github.com/adafruit/Wippersnapper_Components/issues/228
> Publish DS2484

- components/i2c/ina260/definition.json
Adds the defintion for the INA260 https://www.adafruit.com/product/4226
> Add definition for INA260

- components/i2c/qmc5883p/definition.json
Adds the QMC5883P
Linked to https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/802
> add(qmc5883p): raw event only for now
